### ISSUE TITLE
Example diverging

### ISSUE THREAD

**Issue by AadilLatif** [tdcosim/SolarPV-DER-simulation-tool#31]
Hi,

The example PV-DER_wrapper_usage_example seems to be diverging. Can you please have a look? I am following the same implementation for a project and initially thought I had some issue with my implementation. I ended up running the example and results here also seem to diverge.

Best regards,
Aadil

**Comment by sibyjackgrove** [comment]
@AadilLatif By diverging, do you mean `sim1.run_simulation()` is not able to obtain a solution? Could you post a screenshot of the results?
